apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-zlj3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vwxi-tenant/rhtap-demo-app/hacbs-test-project-zlj3@sha256:c979329426355b8deb8e4356fdd964e0499724fd707a09907955188eceb435bd
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
