apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-zlj3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vwxi-tenant/rhtap-demo-app/hacbs-test-project-zlj3@sha256:bf6ded56797cb6eccdf7219fb17dad008b6fb2ab1f815462cb9cfcf11ac7c853
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
