apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-zlj3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-zlj3
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-zlj3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-zlj3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-zlj3
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vwxi-tenant/rhtap-demo-app/hacbs-test-project-zlj3@sha256:bf6ded56797cb6eccdf7219fb17dad008b6fb2ab1f815462cb9cfcf11ac7c853
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
